# Generated by Django 4.0.5 on 2022-06-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imagee',
            new_name='image',
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(blank=True, null=True)),
                ('usability', models.IntegerField(blank=True, null=True)),
                ('content', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.project')),
            ],
        ),
    ]
