# Generated by Django 3.1.3 on 2022-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20220613_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
