# Generated by Django 3.1.3 on 2022-06-13 22:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects_screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media'),
        ),
    ]
